# TD1 : Introduction, exemples d'opérations sur les torch.tensor

Dans pytorch, les données sont organisées sous forme de tensor. Un tenseur est un tableau (ou vecteur) de nombres. Dans les lignes qui vont suivres, nous allons présenter une série d'exemples d'opeérations pouvant être faites avec pytorch.

In [1]:
# Tout d'abord, importer torch
import torch

In [2]:
# Construire un tensor vide de dimension 2x3
x = torch.empty(2, 3)
print(x)

tensor([[4.1760e+21, 1.2812e-11, 3.3608e+21],
        [1.6995e-04, 2.7444e-06, 1.0081e-08]])


In [3]:
# Construire un tensor de valeurs aléatoires
x = torch.rand(3, 3)
print(x)

tensor([[0.2859, 0.4895, 0.9559],
        [0.2774, 0.5200, 0.8233],
        [0.6265, 0.5485, 0.3258]])


In [4]:
# Construire un tensor de zéros
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# Construire un tensor avec des valeurs pré-définies
x = torch.tensor([[1,2],[3,4]])
print(x)
print(x.size())

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


Les tensors s'utilisent comme des vecteurs

In [6]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)
print(x)
print(y)

tensor([[-0.0020, -0.1670,  0.8460],
        [-0.7697, -1.4612, -1.1267]])
tensor([[ 0.1891,  1.4344, -0.8287],
        [-0.9102,  1.5548, -0.8269]])


In [7]:
# Addition terme à terme
print(x+y)

tensor([[ 0.1871,  1.2674,  0.0173],
        [-1.6799,  0.0937, -1.9536]])


In [8]:
# Multiplication terme à terme
print(x*y)

tensor([[-3.6977e-04, -2.3948e-01, -7.0102e-01],
        [ 7.0055e-01, -2.2718e+00,  9.3170e-01]])


In [9]:
# Multiplication par un nombre réel
print(2 * x)

tensor([[-0.0039, -0.3339,  1.6919],
        [-1.5393, -2.9223, -2.2535]])


In [10]:
# Addition avec un nombre réel
print(x+1)

tensor([[ 0.9980,  0.8330,  1.8460],
        [ 0.2303, -0.4612, -0.1267]])


Il y a différentes façon d'accéder aux valeurs d'un tensor

In [11]:
# Obtient le nombre aux coordonnées [0,1] 
print(x[0,1])

# Obtient la première ligne de x
print(x[0])

# Obtient la troisième colonne de x
print(x[:, 2])

tensor(-0.1670)
tensor([-0.0020, -0.1670,  0.8460])
tensor([ 0.8460, -1.1267])


Vous pouvez même aller plus loin et accédez aux valeurs d'un tenseurs respectant certaines conditions

In [12]:
print(x[x > 0])

print("y là où x > 0")
print(y[x > 0])

tensor([0.8460])
y là où x > 0
tensor([-0.8287])


Il existe aussi plein de méthodes sur les tensors.

Par exmple la somme: regarder les différences entre ces trois commandes

In [13]:
print("Sum")
print(x.sum()) # Somme tous les éléments de x
print(x.sum(dim=0)) # Somme uniquement sur la première dimension
print(x.sum(dim=1)) # Somme uniquement sur la deuxième dimension
print(x.sum(dim=1, keepdim=True)) # Somme uniquement sur la deuxième dimension

Sum
tensor(-2.6805)
tensor([-0.7716, -1.6281, -0.2808])
tensor([ 0.6770, -3.3576])
tensor([[ 0.6770],
        [-3.3576]])
